services:
    db:
        image: mysql:latest
        ports:
        - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: abc123
            MYSQL_DATABASE: earthquake_db
        volumes:
        - db:/var/lib/mysql

    earthquake-api:
        build:
            context: ./earthquake-api
            dockerfile: Dockerfile
        ports:
        - "8085:8080"
        depends_on:
        - db
        environment:
        - MYSQL_DB_HOST=db
        - MYSQL_DB_USER=root
        - MYSQL_DB_PASS=abc123
        restart: always
        
volumes:
    db:
